version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: master
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "master"]
      interval: 30s
      timeout: 10s
      retries: 5

  auth-api:
    build:
      context: ../auth-api-core
      dockerfile: ./Dockerfile
    container_name: auth-api
    ports:
      - "5001:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=master;Username=admin;Password=admin
    networks:
      - backend

  router-api:
    build:
      context: ../routes-api-core
      dockerfile: ./Dockerfile
    container_name: router-api
    ports:
      - "5002:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=master;Username=admin;Password=admin
    networks:
      - backend

  van-api:
    build:
      context: ../van-api-core
      dockerfile: ./Dockerfile
    container_name: van-api
    ports:
      - "5003:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=master;Username=admin;Password=admin
    networks:
      - backend

  gateway:
    build:
      context: ../gateway-api-core
      dockerfile: ./Dockerfile
    container_name: gateway
    ports:
      - "6000:80"
    depends_on:
      - auth-api
      - router-api
      - van-api
    environment:
      - OCEL0T_ENV=docker
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
