version: "3.8"

services:
  rabbitmq-dev:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    restart: always
    ports:
      - "19672:5672"
      - "19673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - services-dev
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-dev:
    image: redis:latest
    container_name: redis-dev
    restart: always
    ports:
      - "19379:6379"
    networks:
      - services-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-dev:
    image: postgres:16
    container_name: postgres-dev
    restart: always
    ports:
      - "19432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: master
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - services-dev
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "master"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  services-dev:
    external: true

volumes:
  pgdata:
