version: "3.8"

services:
  auth-api:
    build:
      context: ../../auth-api-core
      dockerfile: ./Dockerfile
    container_name: auth-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=master;Username=admin;Password=admin
    networks:
      - backend

  router-api:
    build:
      context: ../../routes-api-core
      dockerfile: ./Dockerfile
    container_name: router-api
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=master;Username=admin;Password=admin
    networks:
      - backend

  payments-api:
    build:
      context: ../../payments-api-core
      dockerfile: ./Dockerfile
    container_name: payments-api
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=master;Username=admin;Password=admin
    networks:
      - backend

  pessoas-api:
    build:
      context: ../../pessoas-api-core
      dockerfile: ./Dockerfile
    container_name: pessoas-api
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=master;Username=admin;Password=admin
    networks:
      - backend

  gateway:
    build:
      context: ../../gateway-api-core
      dockerfile: ./Dockerfile
    container_name: gateway
    ports:
      - "8000:8080"
    depends_on:
      - auth-api
      - router-api
      - payments-api
      - pessoas-api
    environment:
      - ENV=docker
    networks:
      - backend

networks:
  backend:
    driver: bridge
