version: "3.8"

services:
  auth-api-dev:
    image: apis-auth-api-dev:latest
    build:
      context: ../../auth-api-core
      dockerfile: ./Dockerfile
    container_name: auth-api-dev
    ports:
      - "19001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-dev;Database=auth-db;Username=admin;Password=admin
      - ConnectionStrings__RedisConnection=redis-dev:6379
      - ConnectionStrings__RabbitConnection=rabbitmq-dev
    networks:
      - services-dev

  router-api-dev:
    image: apis-routes-api-dev:latest
    build:
      context: ../../routes-api-core
      dockerfile: ./Dockerfile
    container_name: router-api-dev
    ports:
      - "19002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-dev;Database=routes-db;Username=admin;Password=admin
      - ConnectionStrings__RedisConnection=redis-dev:6379
      - ConnectionStrings__RabbitConnection=rabbitmq-dev
    networks:
      - services-dev

  payments-api-dev:
    image: apis-payments-api-dev:latest
    build:
      context: ../../payments-api-core
      dockerfile: ./Dockerfile
    container_name: payments-api-dev
    ports:
      - "19003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-dev;Database=payments-db;Username=admin;Password=admin
      - ConnectionStrings__RedisConnection=redis-dev:6379
      - ConnectionStrings__RabbitConnection=rabbitmq-dev
    networks:
      - services-dev

  pessoas-api-dev:
    image: apis-pessoas-api-dev:latest
    build:
      context: ../../pessoas-api-core
      dockerfile: ./Dockerfile
    container_name: pessoas-api-dev
    ports:
      - "19004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-dev;Database=pessoas-db;Username=admin;Password=admin
      - ConnectionStrings__RedisConnection=redis-dev:6379
      - ConnectionStrings__RabbitConnection=rabbitmq-dev
    networks:
      - services-dev

  gateway-dev:
    image: apis-gateway-api-dev:latest
    build:
      context: ../../gateway-api-core
      dockerfile: ./Dockerfile
    container_name: gateway-dev
    ports:
      - "19080:8080"
    depends_on:
      - auth-api-dev
      - router-api-dev
      - payments-api-dev
      - pessoas-api-dev
    environment:
      - ENV=Development
    networks:
      - services-dev

networks:
  services-dev:
    external: true
