services:
  auth-api-dev:
    image: 54.163.143.108:5000/auth-api-dev:latest
    container_name: auth-api-dev
    ports:
      - "19001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - services-dev

  router-api-dev:
    image: 54.163.143.108:5000/router-api-dev:latest
    container_name: router-api-dev
    ports:
      - "19002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - services-dev

  payments-api-dev:
    image: 54.163.143.108:5000/payments-api-dev:latest
    container_name: payments-api-dev
    ports:
      - "19003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - services-dev

  pessoas-api-dev:
    image: 54.163.143.108:5000/pessoas-api-dev:latest
    container_name: pessoas-api-dev
    ports:
      - "19004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - services-dev

  gateway-api-dev:
    image: 54.163.143.108:5000/gateway-api-dev:latest
    container_name: gateway-api-dev
    ports:
      - "19005:8080"
    depends_on:
      - auth-api-dev
      - router-api-dev
      - payments-api-dev
      - pessoas-api-dev
    environment:
      - ENV=Development
    networks:
      - services-dev

networks:
  services-dev:
    external: true
