version: "3.8"

services:
  auth-api:
    build:
      context: ../../auth-api-core
      dockerfile: ./Dockerfile
    container_name: auth-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=auth-db;Username=admin;Password=admin
      - ConnectionStrings__RedisConnection=redis:6379
      - ConnectionStrings__RabbitConnection=rabbitmq
    networks:
      - services

  router-api:
    build:
      context: ../../routes-api-core
      dockerfile: ./Dockerfile
    container_name: router-api
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=routes-db;Username=admin;Password=admin
      - ConnectionStrings__RedisConnection=redis:6379
      - ConnectionStrings__RabbitConnection=rabbitmq
    networks:
      - services

  payments-api:
    build:
      context: ../../payments-api-core
      dockerfile: ./Dockerfile
    container_name: payments-api
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=payments-db;Username=admin;Password=admin
      - ConnectionStrings__RedisConnection=redis:6379
      - ConnectionStrings__RabbitConnection=rabbitmq
    networks:
      - services

  pessoas-api:
    build:
      context: ../../pessoas-api-core
      dockerfile: ./Dockerfile
    container_name: pessoas-api
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=pessoas-db;Username=admin;Password=admin
      - ConnectionStrings__RedisConnection=redis:6379
      - ConnectionStrings__RabbitConnection=rabbitmq
    networks:
      - services

  gateway:
    build:
      context: ../../gateway-api-core
      dockerfile: ./Dockerfile
    container_name: gateway
    ports:
      - "8000:8080"
    depends_on:
      - auth-api
      - router-api
      - payments-api
      - pessoas-api
    environment:
      - ENV=docker
    networks:
      - services

networks:
  services:
    external: true
